version: '3'
services:
    p1-api-php:
        build: .
        container_name: p1-api-php
        restart: always
        networks: 
          - p1devnet
    p1-api-nginx:
        container_name: p1-api-nginx
        image: nginx:1.15.4
        networks: 
          - p1devnet
        ports:
            - "180:80"
            - "1443:443"
        restart: always
        volumes:
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
        depends_on:
            - "p1-api-php"

    p1-api-mongo:
        image: mongo:4.1.3
        container_name: p1-api-mongo
        networks: 
          - p1devnet
        restart: always
        volumes:
            - p1-admin-mongo:/data/db
        ports:
            - "27017:27017"

volumes:
  p1-admin-mongo:
    external: true

networks:
  p1devnet:
    external: true