imports:
  - { resource: listeners.yml }
  - { resource: parameters.yml }
  - { resource: services.yml }
  - { resource: security.yml }
  - { resource: packages/sonata_media.yml }

framework:
  secret: "%default_secret%"
  translator: { fallbacks: ["%default_locale%"] }
  templating:
    engines: ['twig']
  validation: { enable_annotations: true }
  serializer: { enable_annotations: true }
  csrf_protection: false
  session:
    handler_id:  ~
    cookie_lifetime: 43200
  form: ~
  test: ~

twig:
  debug: "%kernel.debug%"
  strict_variables: "%kernel.debug%"

monolog:
  handlers:
    main:
      type: stream
      path: "%kernel.logs_dir%/%kernel.environment%.log"
      level: debug

doctrine_mongodb:
  connections:
    default:
      server: "%mongodb_server%"
      options: {}
  default_database: "%mongodb_database%"
  document_managers:
    default:
      mappings:
        App:
          type: annotation
          dir: "%kernel.root_dir%/../src/Core/Document/"
          prefix: Core\Document
          alias: Core
        SonataMediaBundle: ~
        ApplicationSonataMediaBundle: ~

lexik_jwt_authentication:
  secret_key: "%env(base64:JWT_SECRETS_FILE_SOURCE)%"
  public_key: "%env(base64:JWT_PUBLIC_FILE_SOURCE)%"
  pass_phrase: "%jwt.pass.phrase%"
  token_ttl: "%jwt.ttl.access_token%"
  user_identity_field: id
  token_extractors:
    authorization_header:
      enabled: true
      prefix: BEARER
      name: Authorization
