services:
  core.listener.json_request_transform:
    class: Core\Listener\JsonRequestTransformListener
    tags:
    - { name: "kernel.event_listener", event: "kernel.request", method: "onKernelRequest", priority: 100 }

  core.listener.acess_control_header_modify:
    class: Core\Listener\AccessControlHeadersModify
    tags:
    - { name: "kernel.event_subscriber" }
